#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory

source /etc/device_config
. /bin/readsettings.sh >/dev/null

create_system_files () {

	UDHCPD_CONF=/etc/udhcpd.conf
	CONF=/opt/config.txt
	IFAC=/etc/network/interfaces

	HOSTNAME=`fw_printenv -n hostname 2> /dev/null || cat /etc/hostname`
	echo $HOSTNAME > /etc/hostname

	IPADDR=`fw_printenv -n ipaddr 2> /dev/null || echo 192.168.2.1`
	IPADDR_HOST=`fw_printenv -n ipaddr_host 2> /dev/null || echo 192.168.2.10`
	NETMASK=`fw_printenv -n netmask 2> /dev/null || echo 255.255.255.0`

	ETH_IPADDR=`fw_printenv -n ipaddr_eth 2> /dev/null`
	ETH_NETMASK=`fw_printenv -n netmask_eth 2> /dev/null || echo 255.255.255.0`

	WLAN_SSID=`fw_printenv -n ssid_wlan 2> /dev/null || echo PlutoWeb`
	WLAN_PWD=`fw_printenv -n pwd_wlan 2> /dev/null`
	WLAN_IPADDR=`fw_printenv -n ipaddr_wlan 2> /dev/null || echo 172.20.0.1`

	XO_CORRECTION=`fw_printenv -n xo_correction 2> /dev/null`
	UDC_HANDLE_SUSPEND=`fw_printenv -n udc_handle_suspend 2> /dev/null || echo 0`

	### /etc/udhcpd.conf ###
	echo "start $IPADDR_HOST" > $UDHCPD_CONF
	echo "interface usb0" >> $UDHCPD_CONF
	echo "option subnet $NETMASK" >> $UDHCPD_CONF
	if [ -e /dev/wlan0 ]; then
		echo "start $WLAN_IPADDR""0" > $UDHCPD_CONF
		echo "interface wlan0" >> $UDHCPD_CONF
		echo "option subnet $NETMASK" >> $UDHCPD_CONF
	fi

	### /etc/network/interfaces ###
	echo -e "auto lo\n""iface lo inet loopback\n" > $IFAC
	if [ -e /dev/wlan0 ]; then
		echo -e "auto wlan0\n""iface wlan0 inet static" >> $IFAC
		echo -e "\taddress $WLAN_IPADDR\n""\tnetmask $NETMASK\n" >> $IFAC
	else
		echo -e "auto usb0\n""iface usb0 inet static" >> $IFAC
		echo -e "\taddress $IPADDR\n""\tnetmask $NETMASK\n" >> $IFAC
	fi

	echo -e "auto eth0" >> $IFAC
	if [ -n "$ETH_IPADDR" ]
	then
		echo -e "iface eth0 inet static" >> $IFAC
		echo -e "\taddress $ETH_IPADDR\n""\tnetmask $ETH_NETMASK\n" >> $IFAC
	else
		echo -e "iface eth0 inet dhcp\n" >> $IFAC
	fi

	### /etc/wpa.conf ###
	if [ -n "$WLAN_SSID" ]
	then
		if [ -n "$WLAN_PWD" ]
		then
			wpa_passphrase $WLAN_SSID $WLAN_PWD > /etc/wpa.conf
		else
			echo "network={" > /etc/wpa.conf
			echo "    ssid=\"$WLAN_SSID\"" >> /etc/wpa.conf
			if [ "$WLAN_SSID" = "PlutoWeb" ]; then
				echo "    mode=2" >> /etc/wpa.conf
			fi
			echo "    key_mgmt=NONE" >> /etc/wpa.conf
			echo "}" >> /etc/wpa.conf
		fi

		echo -e "\twpa-conf /etc/wpa.conf\n" >> $IFAC
	fi

	### /opt/config.txt ###
	echo "# Device Configuration File"$'\r' > $CONF
	echo "# Edit, Save and then Eject the USB Drive"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[PlutoWeb]"$'\r' >> $CONF
	echo "autostart = $autostart"$'\r' >> $CONF
	echo "autoreboot = $autoreboot"$'\r' >> $CONF
	echo "autoupdate = $autoupdate"$'\r' >> $CONF
	echo ""$'\r' >> $CONF
	echo "[OpenWebRX]"$'\r' >> $CONF
	echo "center_freq = $center_freq"$'\r' >> $CONF
	echo "start_freq = $start_freq"$'\r' >> $CONF
	echo "samp_rate = $samp_rate"$'\r' >> $CONF
	echo "start_mod = $start_mod"$'\r' >> $CONF
	echo "rf_gain = $rf_gain"$'\r' >> $CONF
	echo "ppm = $ppm"$'\r' >> $CONF
	echo "web_port = $web_port"$'\r' >> $CONF
	echo "max_clients = $max_clients"$'\r' >> $CONF
	echo "fft_fps = $fft_fps"$'\r' >> $CONF
	echo "fft_size = $fft_size"$'\r' >> $CONF
	echo "fft_voverlap_factor = $fft_voverlap_factor"$'\r' >> $CONF
	echo ""$'\r' >> $CONF
	echo "[SDRHU]"$'\r' >> $CONF
	echo "receiver_location = $receiver_location"$'\r' >> $CONF
	echo "receiver_qra = $receiver_qra"$'\r' >> $CONF
	echo "receiver_asl = $receiver_asl"$'\r' >> $CONF
	echo "receiver_ant = $receiver_ant"$'\r' >> $CONF
	echo "receiver_admin = $receiver_admin"$'\r' >> $CONF
	echo "receiver_gps = $receiver_gps"$'\r' >> $CONF
	echo "sdrhu_key = $sdrhu_key"$'\r' >> $CONF
	echo "sdrhu_public_listing = $sdrhu_public_listing"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[NETWORK]"$'\r' >> $CONF
	echo "hostname = $HOSTNAME"$'\r' >> $CONF
	echo "ipaddr = $IPADDR"$'\r' >> $CONF
	echo "ipaddr_host = $IPADDR_HOST"$'\r' >> $CONF
	echo "netmask = $NETMASK"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[WLAN]"$'\r' >> $CONF
	echo "ssid_wlan = $WLAN_SSID"$'\r' >> $CONF
	echo "pwd_wlan = $WLAN_PWD"$'\r' >> $CONF
	echo "ipaddr_wlan = $WLAN_IPADDR"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[USB_ETHERNET]"$'\r' >> $CONF
	echo "ipaddr_eth = $ETH_IPADDR"$'\r' >> $CONF
	echo "netmask_eth = $ETH_NETMASK"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[SYSTEM]"$'\r' >> $CONF
	echo "xo_correction = $XO_CORRECTION"$'\r' >> $CONF
	echo "udc_handle_suspend = $UDC_HANDLE_SUSPEND"$'\r' >> $CONF
	echo ""$'\r'>> $CONF
	echo "[ACTIONS]"$'\r' >> $CONF
	echo "diagnostic_report = 0"$'\r' >> $CONF
	echo "dfu = 0"$'\r' >> $CONF
	echo "reset = 0"$'\r' >> $CONF
	echo "calibrate = 0"$'\r' >> $CONF
	echo ""$'\r'>> $CONF

	### /www/index.html ###

	#sed -i -e "s/#IP#/$IPADDR/g" -e "s/#HOSTIP#/$IPADDR_HOST/g" -e "s/#NETMASK#/$NETMASK/g" -e "s/#HOSTNAME#/$HOSTNAME/g" -e "s/#SSID_WLAN#/$WLAN_SSID/g" -e "s/#IPADDR_WLAN#/$WLAN_IPADDR/g" -e "s/#IPADDR_ETH#/$ETH_IPADDR/g" -e "s/#NETMASK_ETH#/$ETH_NETMASK/g" /www/index.html /www/img/index_*.html

	}

mkdir -p /run/network

case "$1" in
  start)
	create_system_files
	printf "Starting network: "
	/bin/hostname -F /etc/hostname
	/sbin/ifup -a 2>&1 | logger
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

